---
title:               Laura Diane Hamilton
tagline:             Vice President of Analytics at BayRu, LLC.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Laura Diane Hamilton
linkedin:            lauradhamilton
twitter:             lauradhamilton
github:              lauradhamilton
email:               lauradhamilton@gmail.com
google_analytics_id: UA-38928252-1
