---
title:               Laura Diane Hamilton
tagline:             Technology Executive.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Laura Diane Hamilton
twitter:             lauradhamilton
github:              lauradhamilton
email:               lauradhamilton@gmail.com
google_analytics_id: YOUR_GA_ID